CREATE USER 'shane'@'localhost' IDENTIFIED BY 'S13240sx91';
GRANT ALL PRIVILEGES ON *.* TO 'shane'@'localhost' WITH GRANT OPTION;
CREATE USER 'shane'@'%' IDENTIFIED BY 'S13240sx91';
GRANT ALL PRIVILEGES ON *.* TO 'shane'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE DATABASE dynamic;